"""empty message

Revision ID: 46a0ed88c253
Revises: 31b14999ff49
Create Date: 2016-02-25 00:22:55.101312

"""

# revision identifiers, used by Alembic.
revision = '46a0ed88c253'
down_revision = '31b14999ff49'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('role_relationship',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column(u'news', sa.Column('permission', sa.PickleType(), nullable=True))
    op.alter_column(u'news', 'context',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    #op.create_unique_constraint(None, 'tags', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.alter_column(u'news', 'context',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.drop_column(u'news', 'permission')
    op.drop_table('role_relationship')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    ### end Alembic commands ###
