"""empty message

Revision ID: f9ebb6ad0d3c
Revises: 46a0ed88c253
Create Date: 2016-07-20 20:40:22.316233

"""

# revision identifiers, used by Alembic.
revision = 'f9ebb6ad0d3c'
down_revision = '46a0ed88c253'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_relationship')
    op.drop_table('roles')
    op.drop_table('role_relationship')
    op.drop_table('tags')
    op.add_column('comments', sa.Column('parsed_context', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('parsed_context', sa.Text(), nullable=True))
    op.drop_column('news', 'permission')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('permission', sa.BLOB(), nullable=True))
    op.drop_column('news', 'parsed_context')
    op.drop_column('comments', 'parsed_context')
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('role_relationship',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'role_relationship_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'role_relationship_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tag_relationship',
    sa.Column('news_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tags_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_id'], [u'news.id'], name=u'tag_relationship_ibfk_1'),
    sa.ForeignKeyConstraint(['tags_id'], [u'tags.id'], name=u'tag_relationship_ibfk_2'),
    sa.PrimaryKeyConstraint('news_id', 'tags_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
